language: php

php: 
  - 5.3
  - 5.4

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs --standard=PSR2 src/ -p
